AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for URL Shortener service'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  UrlMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-url-mappings'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: createdAt-index
          KeySchema:
            - AttributeName: createdAt
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: URLShortener
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: Database

Outputs:
  TableName:
    Description: 'Name of the DynamoDB table'
    Value: !Ref UrlMappingsTable
    Export:
      Name: !Sub '${Environment}-url-mappings-table-name'
  
  TableArn:
    Description: 'ARN of the DynamoDB table'
    Value: !GetAtt UrlMappingsTable.Arn
    Export:
      Name: !Sub '${Environment}-url-mappings-table-arn'